### ISSUE TITLE
Simplify makefile

### ISSUE THREAD

**Issue by andreineculau** [bigcompany/know-your-http#12]
Just to DRY up [the current one](https://github.com/bigcompany/know-your-http/blob/e64ca466173c1d5255df366426b63a128f5432c8/Makefile) a bit.
Tested only on OSX.

``` make
posters := headers.tex methods.tex status-codes.tex
postersPDF := $(posters:.tex=.pdf)
postersPNG := $(posters:.tex=.png)

.PHONY: all pdfs pngs clean %.pdf %.png

all: pdfs

pdfs: $(postersPDF)

pngs: $(postersPNG)

clean:
    @git clean -xfd
    @rm -f $(postersPDF) $(postersPNG)

$(postersPDF): $(1)

$(postersPNG): $(1)

%.pdf: %.tex
    @$(eval input := $<)
    @$(eval output := $@)
    @pdflatex -shell-escape -interaction=nonstopmode -halt-on-error $(input)

%.png: %.pdf
    @$(eval input := $<)
    @$(eval output := $@)
    @convert $(input) -resize 20208x $(output)
```

**Comment by jfhbrook** [comment]
Can you resubmit this as a true pull request?

**Comment by andreineculau** [comment]
Nope, but if you want to keep track of authors, this should do the job

``` bash
# modify make
git add Makefile
git commit --author="Andrei Neculau <andrei.neculau@gmail.com>"
```

**Comment by defunctzombie** [comment]
@andreineculau dude, wtf? Github works on pull requests. Why would you go through the trouble of doing the work and then not take the trivial effort to work with the maintainer to get it accepted?

**Comment by jfhbrook** [comment]
I'm reopening this, if only because the original concern is legitimate.

**Comment by andreineculau** [comment]
@shtylman afaik github works on top of git, not on pull requests.

RE: why?
because I cloned it and started to play with it locally i.e. I didn't fork it "the github way". Forgive me for being too honest (it's not meant as a figure of speech), but I have no interest in this repo (not for one, but several reasons) to go through "the trivial effort" (i.e. fork, git clone/remote add, push, pull request). You should fork a repo if you intend to maintain the forked repo (disclaimer: that's a note2self as well), not just because you want to improve another repo (you have github patches for that, and ways to attribute commits to authors other than yourself). Otherwise "the trivial effort" is also accompanied by deleting the forked repo after the pull request. That said, I'm not disagreeing with you in terms of ~_that's what github hints at_. But to jump at me on that basis, it's totally uncalled for.

I contributed to this repo by 1) opening an issue 2) publishing code 3) providing a way to attribute this code to me. Beyond that, the author/maintainer of the repo is free to do whatever. Treat it as a non-issue, ignore the patch, attribute the patch to himself, make a better patch based on the issue, etc. That is open-source. I have no concern, and I have no idea why the author would treat an issue as a "concern". It could be an improvement, a question, whatever. Some people take a github issue as a challenge to teach themselves/others something. In this case there's more than 1 thing one can learn about the diff between makefiles. Concern? No. Continue running the current makefile, write code that does the same thing twice. _I do not really care_ (no offense intended for this or any other repo's author), or at least nobody should care. **I went through "the trouble" of copy-pasting this crappy code here (I'm sure there are other&better makefile gurus out there) with no intent of receiving attribution for it.**

PS: One could extremely well point out that instead of "arguing" along this "long" github comment, in the same/smaller timeframe, I could have just gone through "the trivial effort", but that's really not the point, and I hope some people at least understand.

**Comment by jfhbrook** [comment]
I'm really really irritated to see this stuff in my issue tracker.
