### ISSUE TITLE
Transfer-Encoding description incorrect

### ISSUE THREAD

**Issue by strtok** [bigcompany/know-your-http#16]
Here's the description on the poster:

Transfer-Encoding The method of encoding used to transfer the response (defined methods: chunked, compress, deflate, gzip, identity)

compress, deflate, gzip are all possible values of the Content-Encoding header, not Transfer-Encoding. The only possible values for Transfer-Encoding are chunked or identity.

**Comment by jfhbrook** [comment]
Sharp eye! I'll confirm and fix this when I get to the office.

**Comment by jfhbrook** [comment]
Took a look, according to iana the current value is correct: http://www.iana.org/assignments/http-parameters/http-parameters.xhtml (scroll down)
